# Generated by Django 2.2.5 on 2019-11-05 23:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import interfacecasos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=200, verbose_name='Nome do cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Expected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected', models.CharField(max_length=120, verbose_name='Resultado Esperado')),
            ],
            options={
                'verbose_name': 'Resultado Esperado',
                'verbose_name_plural': 'Resultados Esperados',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('num_feature', models.CharField(default=interfacecasos.models.count, editable=False, max_length=20, verbose_name='Número da funcionalidade')),
                ('date_to_finish', models.DateTimeField(verbose_name='Data para finalizar')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 5, 23, 51, 59, 363901, tzinfo=utc), verbose_name='Data de Criação')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('date_finished', models.DateTimeField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('min_cases', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Quantidade mínima de casos')),
            ],
            options={
                'verbose_name': 'Funcionalidade',
                'verbose_name_plural': 'Funcionalidades',
            },
        ),
        migrations.CreateModel(
            name='Precondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condittion', models.CharField(max_length=120, verbose_name='Pré-Condição')),
            ],
            options={
                'verbose_name': 'Pré-Condição',
                'verbose_name_plural': 'Pré-Condições',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128, verbose_name='Nome')),
                ('data_de_nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('telefone_celular', models.CharField(max_length=15, unique=True, verbose_name='Telefone celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('cargo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interfacecasos.Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Lida')),
                ('pending', models.BooleanField(default=True, verbose_name='Pendente')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interfacecasos.Feature')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interfacecasos.Profile'),
        ),
        migrations.AddField(
            model_name='feature',
            name='colaborator',
            field=models.ManyToManyField(blank=True, related_name='colaborator', to='interfacecasos.Profile'),
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_componente', models.CharField(max_length=120, verbose_name='Componente a ser testado')),
                ('qtd', models.CharField(max_length=50, null=True, verbose_name='Quantidade mínima de casos necessários')),
                ('feature', models.ManyToManyField(blank=True, to='interfacecasos.Feature', verbose_name='Funcionalidade')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('num_case', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Número do caso')),
                ('precondition', models.CharField(max_length=250, verbose_name='Pré-Condição')),
                ('inputs', models.CharField(blank=True, default='Nenhuma', max_length=250, null=True, verbose_name='Entradas')),
                ('action', models.CharField(max_length=250, verbose_name='Ação')),
                ('expected', models.CharField(max_length=250, verbose_name='Resultado Esperado')),
                ('postcondition', models.CharField(max_length=250, verbose_name='Pós-Condição')),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 11, 5, 23, 51, 59, 443686, tzinfo=utc), verbose_name='Data de Criação')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interfacecasos.Componentes')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interfacecasos.Feature')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
            },
        ),
    ]
