# Generated by Django 2.2.5 on 2019-11-06 00:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interfacecasos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 59, 37, 938305, tzinfo=utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 0, 59, 31, 618932, tzinfo=utc), verbose_name='Data de Criação'),
        ),
    ]
