# Generated by Django 2.2.4 on 2019-10-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfacecasos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='colaborator',
            field=models.ManyToManyField(blank=True, related_name='colaborator', to='interfacecasos.Profile'),
        ),
    ]
