# Generated by Django 2.2.5 on 2019-11-06 02:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interfacecasos', '0002_auto_20191105_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 2, 19, 32, 278464, tzinfo=utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 6, 2, 19, 28, 15862, tzinfo=utc), verbose_name='Data de Criação'),
        ),
    ]
