# Generated by Django 2.2.5 on 2019-10-30 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interfacecasos', '0002_feature_colaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False, verbose_name='Lida')),
                ('pending', models.BooleanField(default=True, verbose_name='Pendente')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='interfacecasos.Feature')),
            ],
        ),
    ]
