# Generated by Django 2.2.5 on 2019-11-03 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interfacecasos', '0004_notification_requester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 22, 37, 53, 128913, tzinfo=utc), verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 22, 37, 53, 27184, tzinfo=utc), verbose_name='Data de Criação'),
        ),
    ]
